version: "3.7"

services:
  ecommerce_node:
    image: node:14.19.1
    working_dir: /home/node/app
    volumes:
      - ./exercise-3-back-end/:/home/node/app
    ports:
      - 3001:3001
    #depends_on:
      #- saks_database
    #command: bash -c "npm install && ./wait-for-it.sh -t 0 saks_database:3306 -- npm run migrate && npm run seed && npm run start"
    command: bash -c "npm install && npm run dev"
    # command: bash -c "npm install && npm run migrate && npm run seed && npm run start"
    networks:
      - ecommerce_network

  ecommerce_next:
    image: node:14.19.1
    working_dir: /home/node/app
    volumes:
      - ./exercise-3-front-end/:/home/node/app
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
    networks:
      - ecommerce_network

  mongo:
    image: mongo
    restart: always
    #ports:
    #  - 27017:27017
    networks:
      - ecommerce_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
